sudo: required
services:
  - docker

before_install:
  - docker build -t arn197/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true arn197/docker-react npm run test

deploy:
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-205314270384"
  bucket_path: "docker-react"
  on:
    branch: master
